// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATW4TNNfME1c_61wmudAAcbcKNdVR7FSk',
    appId: '1:261998026200:web:64042d8c49500c8e4fe6ad',
    messagingSenderId: '261998026200',
    projectId: 'movie-ticket-a5c4e',
    authDomain: 'movie-ticket-a5c4e.firebaseapp.com',
    storageBucket: 'movie-ticket-a5c4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlohwOjWiryRdY0wImufYpAH7yXxzRfjw',
    appId: '1:261998026200:android:9048bcdc66ff53424fe6ad',
    messagingSenderId: '261998026200',
    projectId: 'movie-ticket-a5c4e',
    storageBucket: 'movie-ticket-a5c4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmK93Mo-d9q-RL4CnPyQRVTygpgSiX3o',
    appId: '1:261998026200:ios:13ccb8c6be45f82d4fe6ad',
    messagingSenderId: '261998026200',
    projectId: 'movie-ticket-a5c4e',
    storageBucket: 'movie-ticket-a5c4e.appspot.com',
    iosBundleId: 'com.example.movieTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmK93Mo-d9q-RL4CnPyQRVTygpgSiX3o',
    appId: '1:261998026200:ios:13ccb8c6be45f82d4fe6ad',
    messagingSenderId: '261998026200',
    projectId: 'movie-ticket-a5c4e',
    storageBucket: 'movie-ticket-a5c4e.appspot.com',
    iosBundleId: 'com.example.movieTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATW4TNNfME1c_61wmudAAcbcKNdVR7FSk',
    appId: '1:261998026200:web:a6bfa77e89a22f1b4fe6ad',
    messagingSenderId: '261998026200',
    projectId: 'movie-ticket-a5c4e',
    authDomain: 'movie-ticket-a5c4e.firebaseapp.com',
    storageBucket: 'movie-ticket-a5c4e.appspot.com',
  );
}
